#!/bin/bash

BASEDIR=$(dirname "$0")
printf " \nRunning in BASEDIR : $BASEDIR\n"

printf " \nPlease enter the port\n"
read port

printf "\n# Entered port: ${port}\n"

printf "\nPlease enter the username\n"
read username

printf "\n# Entered username: ${username}\n"

printf "\nPlease enter the IP\n"
read selectedip


printf "\n# Entered ip: ${selectedip}\n"
my_exit_port $port $selectedip $username
my_connect_port $port $selectedip $username